### ISSUE TITLE
to_timeseries() column mismatch

### ISSUE THREAD

**Issue by dcrystalj** [onysos/django-composite-foreignkey#2]
I am not sure how this lib works, but using this composoite foreign column i cannot map django model to pandas model using this lib https://github.com/chrisdev/django-pandas.
Somehow number of columns is different.

**Comment by ornoone** [comment]
this lib is a wrapper to map multiple columns to multiple columns  instead of one to one. 

for this to work, your current model must already have some fields with values matching a remote one with equivalent fields. you drop the CompositeForeignKey in your module and this key will retrive the remote instance like a foreignkey would. 

it is always better to use a django's ForeignKey to map to the primarykey of a remote model. this lib was created to work with legacy database with schema that had composite foreign key. don't create your own models with composite foreign key, it's aways  better to just create a ForeignKey.

**Comment by dcrystalj** [comment]
I think problem occurs when i set ```verbose``` to ```False``` (model.to_timeseries(index='time', verbose=False)), It does not try to put foreign model intoto dataframe but value that is in db. I guess using this lib it should provide some concatenated (composited) replacement to have that missing column.
